workflows:
  android-build:
    name: Build Dot Android APK
    max_build_duration: 45
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
